# Generated by Django 4.2.7 on 2023-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vacancy", models.IntegerField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("phone", models.CharField(default="nil", max_length=15)),
                ("mess_availability", models.CharField(default="NO", max_length=15)),
                (
                    "distance_from_college",
                    models.FloatField(default=0.0, max_length=15),
                ),
            ],
        ),
    ]
